# Generated by Django 5.0.3 on 2024-03-04 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('unit', models.CharField(choices=[('kg', 'Kilogram'), ('lbs', 'Pounds'), ('oz', 'Ounces'), ('g', 'Grams')], max_length=50)),
                ('cost_per_unit', models.DecimalField(decimal_places=2, max_digits=6)),
                ('pack_size', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
            ],
        ),
    ]
