# Generated by Django 5.0.3 on 2024-03-04 23:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_category_inventoryitem_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('contact_info', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='pack_size',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Specify pack size in the selected unit of measure', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_items', to='inventory.supplier'),
        ),
    ]
