# Generated by Django 5.0.3 on 2024-03-23 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierslist',
            name='company',
            field=models.CharField(default='CompanyA', max_length=100),
        ),
    ]
