# Generated by Django 5.0.3 on 2024-03-23 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier_management', '0003_alter_supplierslist_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier_List',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('phone', models.IntegerField()),
                ('email', models.EmailField(max_length=100)),
                ('address', models.CharField(max_length=255)),
                ('company', models.CharField(default='CompanyA', max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='SuppliersList',
        ),
    ]
